---
global:
  owner: None
  location: "US"
  regions:
    - &primaryregion "us-central1"
    - &drregion "us-east4"
  remote_state:
    bucket_name: "statebucket" #replace this value
  billing_account: "0088888A-0A777777-11111" #replace this value
  parent_org_id: &org_id "99999999999" #replace this value
  host_project:
    parent: folders/00000000000 #replace this value
    name: &hostproj "p2-rr666-host-shvpcn" #replace this value
    id: *hostproj
  service_projects:
    gke_proj:
      project_name:  &gke_proj_name "s2-rr666-service-gke" #replace this value
      subnets:
        - name: gke-subnet01-use
          region: "us-east4"
        - name: gke-subnet01-usc
          region: "us-central1"
    gce_proj:
      project_name: &gce_proj_name "s2-rr666-service-gce" #replace this value
      subnets:
        - name: gce-subnet01-use
          region: "us-east4"
        - name: gce-subnet01-usc
          region: "us-central1"
    cldsql_proj:
      project_name: &cldsql_proj_name "s2-rr666-service-cldsql" #replace this value
      subnets: []
  services: # common services added to projects
    - container.googleapis.com
    - sql-component.googleapis.com
    - dns.googleapis.com
    - servicenetworking.googleapis.com
    - compute.googleapis.com
    - iam.googleapis.com
    - logging.googleapis.com
    - monitoring.googleapis.com
    - sqladmin.googleapis.com
    - securetoken.googleapis.com
    - cloudfunctions.googleapis.com
    - cloudbuild.googleapis.com
    - cloudapis.googleapis.com
    - accesscontextmanager.googleapis.com
    - storage-api.googleapis.com
    - cloudresourcemanager.googleapis.com
  name_prefix:
    - vpcsc
  labels:
    solutionprovider: harinder
    solution: vpcsc
prod_workloads:
  prd:
    region: *primaryregion
    name:
      - prodprimary
      - prd
    labels:
      env: prodprimary
    gce:
      name:
        - gce01
      project_name: *gce_proj_name
      subnetwork:
        name: "gce-subnet01-usc"
        project_name: *hostproj

vpcsc:
  service_perimeters: #add or remove service_perimeters here
    perimeter1:
      perimeter_name: "regular_vpcsc_perimeter_1" #name of the perimeter
      protected_project_ids: #project ids protected by perimeter
        - *gce_proj_name 
        - *gke_proj_name 
        - *cldsql_proj_name
        - *hostproj
      protect_xvpc: true # true means add shared vpc network to perimeter
      restricted_services: # services to be restricted by perimeter
        - container.googleapis.com
        - dns.googleapis.com
        - compute.googleapis.com
        - iam.googleapis.com
        - logging.googleapis.com
        - monitoring.googleapis.com
        - sqladmin.googleapis.com
        - cloudfunctions.googleapis.com
        - cloudbuild.googleapis.com
        - networkconnectivity.googleapis.com
        - networkmanagement.googleapis.com
        - networksecurity.googleapis.com
        - networkservices.googleapis.com
        - storage.googleapis.com
      access_policy_name: "accesspolicy1" #name of access policy
      allowed_egress_projects: [] #list of the project to which egress is allowed
    perimeter2:
      perimeter_name: "regular_vpcsc_perimeter_2"
      protected_project_ids: []
      protect_xvpc: false
      restricted_services:
        - container.googleapis.com
        - compute.googleapis.com
        - iam.googleapis.com
        - logging.googleapis.com
        - monitoring.googleapis.com
        - sqladmin.googleapis.com
        - networkconnectivity.googleapis.com
        - networkmanagement.googleapis.com
        - networksecurity.googleapis.com
        - networkservices.googleapis.com
        - storage.googleapis.com
      access_policy_name: "accesspolicy2"
      allowed_egress_projects: []
  parent_org_id: *org_id 
  access_policy_name: "accesspolicy1"
  allowed_identities: #list of identities allowed in ingress and access level
    - "user:harinderjit.singh@sourcedgroup.com" #replace this value
  access_level:
    allowed_subnets: #list of  allowed IPS/ subnets in  access level
      - "166.48.58.175/32" #replace this value
    name: "terraform_members"
    allowed_regions: #list of  allowed locations in  access level
      - "US"
      - "CA"
